DarkPlasma_SealItemCommand:
  name: DarkPlasma_SealItemCommand
  year: 2021
  license: MIT
  histories:
    - date: 2022/03/31
      version: 1.0.3
      description: 'TemplateEvent.jsと併用すると戦闘テストできない不具合を修正'
    - date: 2021/07/05
      version: 1.0.2
      description: 'MZ 1.3.2に対応'
    - date: 2021/06/22
      version: 1.0.1
      description: 'サブフォルダからの読み込みに対応'
    - date: 2021/05/14
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'アイテムコマンドを封印する'
  parameters: []
  commands: []
  structures:
  dependencies:
    base:
    orderAfter:
    orderBefore:
  help:
    ja: |
      メモ欄に<sealItemCommand>と入力したマップにおいて、
      アイテムコマンドを戦闘/メニュー共に使用不可にします。
