# main menu navigation
menu:
  Home: /
  About: ./2021/12/30/about
  Archive: ./archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  twitter: elleonard_f
  github: elleonard

user:
  name: DarkPlasma (NPlasma)
  avatar: /img/lily300.jpg
  location:
  description:
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: elleonard/DarkPlasma-blog-comments # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: dark # Default value is auto

# Miscellaneous
favicon: /favicon/favicon.ico

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png
