DarkPlasma_ClassSkillMeta:
  name: DarkPlasma_ClassSkillMeta
  year: 2021
  license: MIT
  histories:
    - date: '2021/10/10'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '職業の習得スキルのメモ欄にメタデータを登録する'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      職業の習得するスキル一覧のメモ欄に、
      他の各種データ同様にメタデータを登録できるようにします。

      例えば、習得するスキルのメモ欄に <a:AAA> と記述すると
      $dataClasses[クラスID].learnings[習得スキルindex].meta.a に
      "AAA" が設定されます。
      booleanに関しても、その他各種データのメタデータ同様の仕様で設定されます。
