DarkPlasma_EscapePenalty:
  name: DarkPlasma_EscapePenalty
  version: '1.0.0'
  year: 2020
  license: MIT
  histories:
    - date: '2020/08/27'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '逃走にペナルティを与える'
  parameters:
    - param: loseGoldRate
      text: 落とすお金割合（％）
      desc: 逃走成功時に落とすお金（所持金に対する割合％）
      type: number
      default: 1
    - param: loseGoldMessage
      text:
        ja: 落としたメッセージ
      desc:
        ja: お金を落とした際のメッセージ。{gold}は落としたお金の量、{unit}はお金の単位に変換される。
      type: string
      default: '{gold}{unit}落としてしまった！'
  commands: []
  structures:
  help:
    ja: |
      逃走成功時にペナルティを与えます。
