DarkPlasma_ConsumeItemImmediately:
  name: DarkPlasma_ConsumeItemImmediately
  year: 2020
  license: MIT
  histories:
    - date: '2020/12/14'
      version: '1.0.1'
      description: 'jsdocの型修正'
    - date: '2020/09/11'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '戦闘でアイテムを選択した際、即座に消費する'
  parameters: []
  commands: []
  structures:
  help:
    ja: |
      戦闘でアイテムを選択した際、即座に消費しているように見せます。
